stages:
  - build
  - active_sites
  - render
  - update_metadata

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # push runs  (manual jobs only)
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - when: never

# default:
#   # Activate the pixi environment before each CI job, by-default
#   # Means we don't need to add "pixi run" before every Rscript/Python command
#   before_script:
#     - eval "$(pixi shell-hook)"

variables:
  IMAGE: $CI_REGISTRY_IMAGE:latest
  # API_USGS_PAT: $API_USGS_PAT
  REQUIRED_PERCENTILES: "0,5,10,25,50,75,90,95,100"
  GW_MIN_YEARS_PER_YDAY: "10"
  GW_PCODES: "72019,62611,62610,72150,72229,62600,30210,62613,62612,72231,72232,72230,72227,72228,72226,61055,62601"
  GW_STAT_IDS: "00003,00001"
  GW_COMP_PERIOD_IDS: "Daily"
  SF_MIN_YEARS_PER_YDAY: "20"
  SF_PCODES: "00060,00065"
  SF_STAT_IDS: "00003"
  SF_COMP_PERIOD_IDS: "Daily"

# ---------- build image  ----------
build-image:
  stage: build
  image: ${DEVOPS_REGISTRY}usgs/docker:latest
  timeout: 24h
  services:
    - name: ${DEVOPS_REGISTRY}usgs/docker:latest-dind
      alias: docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - Dockerfile
    - when: never
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin $CI_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:BUILD_${CI_COMMIT_SHORT_SHA} .
    # If this is building a git tag, also push the corresponding docker tag
    - if [ -n "${CI_COMMIT_TAG}" ]; then docker tag "${CI_REGISTRY_IMAGE}:BUILD_${CI_COMMIT_SHORT_SHA}" "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"; fi
    - docker push --all-tags ${CI_REGISTRY_IMAGE}
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

# ---------- gw active sites ----------
gw_shard_prep:
  stage: active_sites
  image:
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "gw_weekly"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  timeout: 24h
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run Rscript -e ".libPaths()"
    - pixi run Rscript gw_ci/gw_initial_pull.R ${GW_MIN_YEARS_PER_YDAY} ${GW_PCODES} ${GW_STAT_IDS} ${GW_COMP_PERIOD_IDS}
  artifacts:
    paths:
      - artifacts/gw_shard_table.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

gw_coverage:
  stage: active_sites
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "gw_weekly"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  timeout: 24h
  needs:
    - job: gw_shard_prep
      artifacts: true
  parallel:
    matrix:
      - SHARD_ID: [0, 1, 2, 3, 4] #,5,6,7,8,9]
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run Rscript gw_ci/gw_coverage_per_shard.R ${SHARD_ID} ${GW_MIN_YEARS_PER_YDAY} ${REQUIRED_PERCENTILES}
  artifacts:
    paths:
      - artifacts/gw_coverage_${SHARD_ID}.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

gw_coverage_merge:
  stage: active_sites
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "gw_weekly"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  timeout: 24h
  needs:
    - job: gw_coverage
      artifacts: true
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run Rscript gw_ci/gw_coverage_merge.R ${GW_PCODES} ${GW_STAT_IDS}
    - pixi run aws s3 cp artifacts/gw_coverage.parquet s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/stage/
  artifacts:
    paths:
      - artifacts/gw_coverage.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

# ---------- categorize + visualize pipeline ----------

gw_render:
  stage: render
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "gw_daily"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  needs: []
  timeout: 24h
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run aws s3 cp s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/stage/gw_coverage.parquet gw_ci/1_fetch/in/gw_coverage.parquet
    - pixi run aws s3 cp s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/metadata/gw_file_metadata.csv gw_ci/1_fetch/in/gw_file_metadata.csv
    - pixi run Rscript -e "setwd('gw_ci'); targets::tar_make()"
    # Daily categorizations parquet files
    - pixi run aws s3 cp gw_ci/1_fetch/out/ s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/stage/
    # Visualizations
    - pixi run aws s3 cp gw_ci/3_visualize/out/ s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/images/ --recursive
    # Metadata files
    - pixi run aws s3 cp gw_ci/4_update/out/ s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/metadata/ --recursive
  tags:
    - water
    - computational_tools
    - production

# ---------- sf active sites ----------
sf_shard_prep:
  stage: active_sites
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "sf_weekly"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  timeout: 24h
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run python sf_ci/sf_initial_pull.py ${SF_MIN_YEARS_PER_YDAY} ${SF_PCODES} ${SF_STAT_IDS} ${SF_COMP_PERIOD_IDS}
  artifacts:
    paths:
      - artifacts/sf_shard_table.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

sf_coverage:
  stage: active_sites
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "sf_weekly"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  parallel:
    matrix:
      - SHARD_ID: [0, 1, 2, 3, 4] #,5,6,7,8,9]
  needs:
    - job: sf_shard_prep
      artifacts: true
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run python sf_ci/sf_coverage_per_shard.py ${SHARD_ID} ${SF_MIN_YEARS_PER_YDAY} ${REQUIRED_PERCENTILES}
  artifacts:
    paths:
      - artifacts/sf_coverage_${SHARD_ID}.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

sf_coverage_merge:
  stage: active_sites
  image:
    name: $IMAGE
    pull_policy: always
  rules:
    - if: '$PIPELINE_MODE == "sf_weekly"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  needs:
    - job: sf_coverage
      artifacts: true
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run python sf_ci/sf_coverage_merge.py ${SF_PCODES} ${SF_STAT_IDS}
    - pixi run aws s3 cp artifacts/sf_coverage.parquet s3://water-visualizations-prod-website/visualizations/current_conditions/streamflow/data/
  artifacts:
    paths:
      - artifacts/sf_coverage.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - water
    - computational_tools
    - production

sf_render:
  stage: render
  image:
    name: $IMAGE
    pull_policy: always
  timeout: 24h
  rules:
    - if: '$PIPELINE_MODE == "sf_inst"'
    # manual run from push
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
    - when: never
  needs: []
  script:
    - echo "PIPELINE_MODE=${PIPELINE_MODE}"
    - echo "CI_PIPELINE_SOURCE=${CI_PIPELINE_SOURCE}"
    - pixi run aws s3 cp s3://water-visualizations-prod-website/visualizations/current_conditions/streamflow/data/sf_coverage.parquet sf_ci/data/sf_coverage.parquet
    - pixi run aws s3 cp s3://water-visualizations-prod-website/visualizations/current_conditions/streamflow/sf_file_metadata.csv sf_ci/config/sf_file_metadata.csv
    - pixi run snakemake --snakefile sf_ci/Snakefile --cores all --directory sf_ci --config date=$(date +%F)
    - pixi run aws s3 cp sf_ci/data/ s3://water-visualizations-prod-website/visualizations/current_conditions/streamflow/data/ --recursive
    - pixi run aws s3 cp sf_ci/figures/ s3://water-visualizations-prod-website/visualizations/current_conditions/streamflow/figures/ --recursive
    - pixi run aws s3 cp sf_ci/movies/ s3://water-visualizations-prod-website/visualizations/current_conditions/streamflow/movies/ --recursive
  tags:
    - water
    - computational_tools
    - production

sf_update_metadata:
  stage: update_metadata
  image:
    name: $IMAGE
    pull_policy: always
  when: always
  needs:
    - job: sf_render
      artifacts: false
  script:
    - pixi run python sf_ci/sf_update_metadata.py --date $(date +%F)
  tags:
    - water
    - computational_tools
    - production
# pages:
#   stage: pages
#   script:
#     #- cp -r 4_report/out/* public
#     - mv ./current_conditions_site_list_sandbox.html public/index.html
#   artifacts:
#     paths:
#       # The folder that contains  the files to be exposed at the Page URL
#       - public
