stages:
  - build
  - sites
  - baselines
  - frame_data
  - render
  - pages

variables:
  IMAGE: $CI_REGISTRY_IMAGE/current-conditions-pipeline:latest

# ---------- build image ----------
build_image:
  stage: build
  image: docker:27
  services: [docker:27-dind]
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

gw_shard_prep:
  stage: sites
  image: $IMAGE
  script:
    - Rscript build_shard_table.R
  artifacts:
    paths:
      - artifacts/shard_table.parquet

gw_coverage:
  stage: sites
  image: $IMAGE
  needs:
    - job: gw_shard_prep
      artifacts: true
  parallel:
    matrix:
      - SHARD_ID: [0,1,2,3,4,5,6,7,8,9]
  script:
    - Rscript check_coverage_shard.R ${SHARD_ID}
  artifacts:
    paths:
      - artifacts/coverage_${SHARD_ID}.parquet

gw_coverage_merge:
  stage: sites
  image: $IMAGE
  needs:
    - job: gw_coverage
      artifacts: true
  script:
    - Rscript merge_coverage.R
    - aws s3 cp artifacts/gw_active_ts_ids.parquet s3://water-visualizations-prod-website/visualizations/current_conditions/groundwater/
  artifacts:
    paths:
      - artifacts/gw_active_ts_ids.parquet
  # these tags are needed to checkout a runner that has automatic access to AWS
  tags:
    - aws
    - production
    - us-west-2
    - wma

# active_sites_sf:
#   stage: sites
#   image: $IMAGE
#   script: python3 sf_ci/active_sites_streamflow.py
#   rules:
#     - if: $YEARLY_RUN == "true"

# # ---------- ad hoc ----------
# gw_percentile_baseline:
#   stage: baselines
#   image: $IMAGE
#   script: Rscript gw_ci/gw_percentiles.R
#   rules:
#     - if: $BASELINE_RUN == "true"

# sf_percentile_baseline:
#   stage: baselines
#   image: $IMAGE
#   script: python3 sf_ci/sf_percentiles.py
#   rules:
#     - if: $BASELINE_RUN == "true"

# # ---------- daily ----------
# gw_frame_data:
#   stage: frame_data
#   image: $IMAGE
#   script: Rscript gw_ci/gw_frame_data.R
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"

# sf_frame_data:
#   stage: frame_data
#   image: $IMAGE
#   script: python3 sf_ci/sf_frame_data.py
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"

# gw_render:
#   stage: render
#   image: $IMAGE
#   script: Rscript gw_ci/gw_render.R
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"

# sf_render:
#   stage: render
#   image: $IMAGE
#   script: python3 sf_ci/sf_render.py
#   rules:
#     - if: $CI_PIPELINE_SOURCE == "schedule"

# pages:
#   stage: pages
#   script:
#     #- cp -r 4_report/out/* public
#     - mv ./current_conditions_site_list_sandbox.html public/index.html
#   artifacts:
#     paths:
#       # The folder that contains  the files to be exposed at the Page URL
#       - public
