import os
import yaml
import numpy as np
import pandas as pd
from sf_conditions.helper_functions import generate_image_list, find_start_date

# Read in Parameters from YAML
with open("config/sf_current_conditions.yaml", "r") as file:
    params = yaml.safe_load(file)

# Load metadata and generate list of files to make
metadata = pd.read_csv("config/sf_file_metadata.csv", dtype=str, keep_default_na=False)

# Get the date list
image_lists, image_download_list, image_make_list, parquet_list, parquet_download_list = generate_image_list(config["date"], params["interval"], params["image_prefix"], params["parquet_prefix"], metadata)

# set final intended output
rule all:
    input:
        ["movies/sf-" + config["date"] + "-back-" + str(interval)+ ".mp4" for interval in params["interval"]]

# gather the state census boundaries
rule gather_census_data:
    params:
        resolution = params["census_data"]["resolution"],
        year = params["census_data"]["year"]
    output:
        outfile = "data/us_states.geojson"
    script:
        "sf_conditions/fetch/get_conus.py"

# simplify the state census boundaries
rule simplify_census_data:
    params:
        simplify = params["geometry_simplify_percent"]
    input:
        infile = "data/us_states.geojson"
    output:
        outfile = "data/us_states_simplified.geojson"
    shell:
        "mapshaper {input.infile} -simplify {params.simplify}% -o {output.outfile}"

# download images that are available for longest interval
for image_download in image_download_list:
    rule:
        name:
            "image_download: " + image_download
        params:
            s3_url_prefix = params["s3_url_prefix"],
            folder = "figures"
        output:
            s3_file = image_download
        script:
            "sf_conditions/fetch/get_s3.py"

# download streamflow data coverage data
rule download_coverage:
    params:
        s3_url_prefix = params["s3_url_prefix"],
        folder = "data"
    output:
        s3_file = params["coverage_file"]
    script:
        "sf_conditions/fetch/get_s3.py"

# download or generate categorization parquet files
for i, parquet_file in enumerate(parquet_list):
    rule:
        name:
            "parquet_download_generate: " + parquet_file
        params:
            s3_url_prefix = params["s3_url_prefix"],
            s3_url_file = parquet_download_list[i],
            folder = "data"
        input:
            coverage_parquet = params["coverage_file"]
        output:
            parquet_file = parquet_file
        script:
            "sf_conditions/process/sf_categorize_inst_values.py"

# create shadow outline plot 
rule make_shadow_plot:
    params:
        figure_params = params["figure_params"],
        state_params = params["state_params"],
    input:
        simplified_census_file = "data/us_states.geojson",
    output:
        shadow_image_file = "figures/sf-shadow.png"
    script:
        "sf_conditions/plot/plot_shadow.py"

# create sf current conditions plots for the given list of dates
for i, parquet_file in enumerate(parquet_list):
    rule:
        name: 
            "image_make: " + image_make_list[i]
        params:
            figure_params = params["figure_params"],
            marker_params = params["marker_params"],
            state_params = params["state_params"],
        input:
            parquet_file = parquet_file,
            simplified_census_file = "data/us_states.geojson",
            shadow_image_file = "figures/sf-shadow.png"
        output:
            image_file = image_make_list[i]
        script:
            "sf_conditions/plot/plot_sf.py"

# create image list text file with durations for movie
rule animation_list:
    params:
        framerate = params["movie_params"]["framerate"],
    input:
        image_list = lambda wc: image_lists[params["interval"].index(wc.interval)] 
    output:
        frame_list = "data/sf-" + config["date"] + "-back-{interval}.txt"
    script:
        "sf_conditions/plot/generate_frame_list.py"
        
# create a movie from the list of generated images
rule animate_current_conditions:
    input:
        image_list = lambda wc: image_lists[params["interval"].index(wc.interval)],
        frame_list = "data/sf-" + config["date"] + "-back-{interval}.txt"
    output:
        outfile = "movies/sf-" + config["date"] + "-back-{interval}.mp4"
    shell:
        r'''
        ffmpeg -y \
          -safe 0 -f concat -i {input.frame_list} \
          -vsync vfr -pix_fmt yuv420p -vcodec libx264 \
          {output.outfile}
        '''
