import os
import re
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta


def generate_image_list(
    end_date_str,
    intervals,
    image_prefix,
    parquet_prefix,
    metadata,
    column="desktop_CONUS_image_file",
):
    """Generates the list of images."""

    max_delta = timedelta(0)
    image_lists = []
    for interval in intervals:
        # `end_date_str` based on `date` argument to Snakemake
        # Use snakemake --cores all --config date="YYYY-MM-DD"
        end_date = datetime.strptime(end_date_str, "%Y-%m-%d").date()
        start_date = find_start_date(end_date, interval)
        delta = end_date - start_date

        # Generate list of dates
        date_list = []
        current = start_date
        while current <= end_date:
            date_list.append(current.strftime("%Y-%m-%d"))
            current += timedelta(days=1)

        image_list = [image_prefix + str(date) + ".png" for date in date_list]
        image_lists += [image_list]
        temp_parquet_list = [parquet_prefix + str(date) + ".parquet" for date in date_list]

        # image_list is contains all image filepaths for a specified interval's animation
        # image_lists is a list of image_lists for each interval

        # this list is from the maxiumum interval
        if delta > max_delta:
            max_delta = delta

            # s3_image_list is a list of all the image urls from the metadata file, "" will be listed if the image does not exist
            # parquet_list is a list of the categorized data used to make each day's images
            s3_image_list = [
                metadata.loc[metadata["date"] == d, column].values[0]
                if d in metadata["date"].values
                else ""
                for d in date_list
            ]
            s3_parquet_list = [
                metadata.loc[metadata["date"] == d, "parquet_file"].values[0]
                if d in metadata["date"].values
                else ""
                for d in date_list
            ]

            # image_download_list contains all images to be downloaded from s3 in the largest interval. They have already been made.
            # image_make_list contains all images to be generated by this pipeline.
            # parquet_list contains all the data needed to make the images in image_make_list
            # parquet_download_list contains all the data urls needed to make the images in image_make_list, "" (blank) means it needs to be generated
            image_download_list = []
            image_make_list = []
            parquet_list = []
            parquet_download_list = []
            # parquet_make_list = []
            for j, s3_image in enumerate(s3_image_list):
                if s3_image == "":
                    image_make_list += [image_list[j]]
                    parquet_download_list += [s3_parquet_list[j]]
                    parquet_list += [temp_parquet_list[j]]
                else:
                    image_download_list += [image_list[j]]

    return image_lists, image_download_list, image_make_list, parquet_list, parquet_download_list


def find_start_date(end_date, interval):
    num, unit = re.match(r"(\d+)([A-Za-z]+)", interval).groups()
    if unit == "d":
        return end_date - relativedelta(days=int(num))
    elif unit == "w":
        return end_date - relativedelta(weeks=int(num))
    elif unit == "m":
        return end_date - relativedelta(months=int(num))
    elif unit == "y":
        return end_date - relativedelta(years=int(num))
    else:
        raise ValueError(f"Invalid interval format")
